GET localhost:8877/v1/api/uaa/tenant/info?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiIxODMxMDgxMTY1OSIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJyb2xlcyI6ImFkbWluIiwidGVuYW50SWQiOjEwMDEsImV4cCI6MTUyNzI3NzkxMywidXNlcklkIjoxMDAxLCJqdGkiOiIxOTA3NDEyZC00Y2FiLTQ1MTMtOWE2Ni03YmRjYTYxZmMwZmYiLCJjbGllbnRfaWQiOiJ3ZWIifQ.kGrHpCqwAmN2BDczgieTNUMuoqSE1bzhHLNyFhr2ODo
####
GET  localhost:8877/api/uaa/register/has-used?phoneNumber=18310811659?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiIxODMxMDgxMTY1OSIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJyb2xlcyI6ImFkbWluIiwidGVuYW50SWQiOjEwMDEsImV4cCI6MTUyNzI3NzkxMywidXNlcklkIjoxMDAxLCJqdGkiOiIxOTA3NDEyZC00Y2FiLTQ1MTMtOWE2Ni03YmRjYTYxZmMwZmYiLCJjbGllbnRfaWQiOiJ3ZWIifQ.kGrHpCqwAmN2BDczgieTNUMuoqSE1bzhHLNyFhr2ODo

###