#### client_credentials模式
POST localhost:9999/open-api/v1/uaa/oauth2/token?grant_type=client_credentials&client_id=11002&client_secret=web

###

GET localhost:9999/open-api/v1/hello

###
OPTIONS http://api.zyou.cn/uaa/oauth/token?grant_type=password&username=13699218273&password=1qaz2wsx&clientId=web&secret=web